### ISSUE TITLE
Convert load.py to use SQLAlchemy

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/cmi-pb-terminology#19]
Please revise the prototype's [load.py](https://github.com/jamesaoverton/cmi-pb-terminology/blob/next/src/script/load.py) to use `bindparam` and `sql_text` from `sqlalchemy.sql.expression` as done in [sprocket run.py](https://github.com/ontodev/sprocket/blob/main/sprocket/run.py).

I would like to output properly escaped SQL strings at this point -- I don't want to execute the SQL from Python yet.

**Comment by beckyjackson** [comment]
I think this is resolved by #21. Can we close this issue?
