### ISSUE TITLE
Finish loading TSVs in load.py script

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/cmi-pb-terminology#20]
After #19.

The current script just loads the table table, but I would like to load the other TSVs: table, column, datatype, prefix, import.

**Comment by beckyjackson** [comment]
I think the [`column.tsv`](https://github.com/jamesaoverton/cmi-pb-terminology/blob/next/src/column.tsv) table is missing a row for the "schema" column of the "column" table. I started to fill it in myself, but I'm not sure what the values for `datatype`, `nulltype`, and `schema` should be for this.

There are also a bunch of columns from [`datatype.tsv`](https://github.com/jamesaoverton/cmi-pb-terminology/blob/next/src/datatype.tsv) missing from `column.tsv`
