### ISSUE TITLE
Prototype loading and validating batches of rows

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/cmi-pb-terminology#22]
Eventually we want to be able to handle large tables using small amounts of memory, so we should design the system from the start to handle rows in batches.

The 'table', 'column', and 'datatype' tables are all special, and should never get too large, so it's fine to load them all into memory at once -- no batching.

In our example, the 'prefix' and 'import' tables should be loaded in batches. We should be able to set the batch size. For testing and development purposes, we will use ridiculously small batch sizes, like 1 or 3.

In particular, the batch size will control the number of rows submitted to `validate_rows` each time it is called.

**Comment by jamesaoverton** [comment]
'foo_invalid' is probably a bad name: various cells in 'foo' may be invalid (e.g. if they fail datatype checks), and various cells in 'foo_invalid' may be valid, so it's not the case the 'foo_invalid' contains all and only invalid data.

We need this secondary table when we have rows that we cannot insert into 'foo' because they will fail certain SQL constraints. Maybe 'foo_fatal' or 'foo_failed' would be better?

**Comment by lmcmicu** [comment]
Resolved by #26
