### ISSUE TITLE
Prototype handling unique constraint

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/cmi-pb-terminology#23]
In the 'structure' column of the 'column' table we want to be able to specify "unique" and "primary" constraints. When calling `validate_row` for a batch of rows, and checking uniqueness for column X, we need to check two things:

1. that the values for column X are unique with respect to the batch
2. that they are also  unique with respect to any data already loaded into that table.

This requires major changes to the current code:

1. we need to give `validate_rows` (read) access to the SQL database
2. we need to actually insert batches of rows as they are validated
3. we need to handle the case where the uniqueness constraint fails

My best idea for handing (3) is to create a second 'foo_invalid' table. 'foo_invalid' would have the same schema as 'foo', except for the unique and primary key constraints. If any cell in a row fails (3) we would insert the whole row into 'foo_invalid', not into 'foo'. So we may want to flag the target table of the whole row somehow. This approach requires an modification to `create_schema` to create the `_invalid` tables. We probably want to also create a view that takes the union of 'foo' and 'foo_invalid', maybe called 'foo_view'.

A disadvantage of this is that we it would take an extra step to add information about the *other* duplicate that was inserted first.

We are not yet considering unique constraints that span multiple columns.

**Comment by jamesaoverton** [comment]
'foo_invalid' is probably a bad name: various cells in 'foo' may be invalid (e.g. if they fail datatype checks), and various cells in 'foo_invalid' may be valid, so it's not the case the 'foo_invalid' contains all and only invalid data.

We need this secondary table when we have rows that we cannot insert into 'foo' because they will fail certain SQL constraints. Maybe 'foo_fatal' or 'foo_failed' would be better?

**Comment by jamesaoverton** [comment]
In SQLite they say ["conflict"](https://www.sqlite.org/lang_conflict.html), so maybe 'foo_conflict' would be the most accurate name.

**Comment by lmcmicu** [comment]
I think `foo_conflict` is the best choice.

**Comment by jamesaoverton** [comment]
Resolved by #26
