### ISSUE TITLE
Prototype handling primary constraint

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/cmi-pb-terminology#24]
Should be pretty much the same as #23.

**Comment by lmcmicu** [comment]
I had just assumed both of these were meant to be covered in #23, actually.

**Comment by lmcmicu** [comment]
(i.e., the description of #23 says: "In the 'structure' column of the 'column' table we want to be able to specify "unique" and "primary" constraints.")

**Comment by jamesaoverton** [comment]
Ok, we'll just use #23 to track this.
