### ISSUE TITLE
Implement new datatype conditions

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/cmi-pb-terminology#31]
On the `next` branch we're currently faking the datatype conditions with hardcoded rules:

https://github.com/jamesaoverton/cmi-pb-terminology/blob/next/src/script/validate.py#L128

I would like to implement these for real. We're currenly using:

- equals
- in
- match
- search
- exclude

I'm not sure these are the best names. The match/search distinction was trying to follow Python, but I always need to look that up. Previous versions of VALVE required `^` and `$` anchors, which are annoying. I intended 'exclude' to mean 'not search' but it could just as easily be read as 'not match'. Suggestions welcome.

Previously we used a grammar for parsing these, but this time we don't have any nested cases to worry about. Maybe string splitting is good enough for now?

Soon we will want to implement conditions for rules, which I think will require `not`, but I'm not sure about `any` and `all`.

**Comment by lmcmicu** [comment]
Since there have been a few commits since this issue was created, it seems that the link in the issue description is now pointing to the wrong place in the code. I am assuming this line is the one that is meant: https://github.com/jamesaoverton/cmi-pb-terminology/blob/c9f8b7a07981c43669dfceaed290f2b20fd1b9e4/src/script/validate.py#L369

**Comment by jamesaoverton** [comment]
At his point we will not implement nesting for these functions. That will (hopefully) keep things simpler for users.

The first nested function we're likely to need is `not`, probably followed by `all`.

**Comment by lmcmicu** [comment]
Closed by #34
