### ISSUE TITLE
Implement rule functionality

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/cmi-pb-terminology#45]
Previous versions of VALVE include a 'rule' table that implements when-then conditions that apply to two columns of a single row. Inter-column validation is important.

But this raises an important design problem: In VALVE the 'rule' table has 'when condition' and 'then condition' columns, where the conditions could be `equals()` or `not(in())` or `under()` etc. The problem is that in the CMI-PB prototype we've been pulling apart the single 'condition' columns into 'nulltype', 'datatype', 'structure', and 'condition'. The separation makes for simple expressions in these columns, but I don't want the 'rule' table to contain multiple columns: 'when nulltype', 'when datatype', 'when structure', 'then nulltype', 'then structure', etc.

Rules are bound to have more complex expressions. Maybe it's fine to continue to have just 'when condition' and 'then condition', where those cells can contain combinations of datatypes, structures, and conditions.

**Comment by lmcmicu** [comment]
Note: The rule table specification for valve is here: https://github.com/ontodev/valve/tree/valve-sql-investigation#rule-table
