### ISSUE TITLE
Try speculative insertion approach to inter-row validation

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/cmi-pb-terminology#48]
We've seen significant performance increases from #44, which applies to intra-row validation (#43). To optimize inter-row validation, especially unique, primary, and foreign key constraints, let's try the following:

1. run intra-row validation on a chunk of rows (e.g. 100 rows)
2. convert the results to a SQL batch INSERT statement
3. inside a SQL transaction, try the insert
4. if the insert succeeds, then (most of?) the inter-row validation passes
5. if the insert fails, we do all the work we're currently doing to find and isolate the problem, then insert again

SQL doesn't give us enough information about **why** an insert fails, so we'll just treat this as a yes/no question. When the insert succeeds, we don't need to run step (5), which should save a lot of work. When the insert fails, we need to do just as much work as we're currently doing. So the question is whether the additional overhead of steps (2) and (3) result in an overall performance win.

**Comment by lmcmicu** [comment]
Actually, I think we are already doing steps 2 and 3. We are already generating only one insert statement per chunk of rows (see [here](https://github.com/jamesaoverton/cmi-pb-terminology/blob/87f9ec7fd1c5125c64469da3943178c3dbf02e9a/src/script/load.py#L455)), and python's `sqlite3` module works with transactions. See, e.g., the `commit()` calls [here](https://github.com/jamesaoverton/cmi-pb-terminology/blob/87f9ec7fd1c5125c64469da3943178c3dbf02e9a/src/script/load.py#L257), [here](https://github.com/jamesaoverton/cmi-pb-terminology/blob/87f9ec7fd1c5125c64469da3943178c3dbf02e9a/src/script/load.py#L275), [here](https://github.com/jamesaoverton/cmi-pb-terminology/blob/87f9ec7fd1c5125c64469da3943178c3dbf02e9a/src/script/load.py#L298), and [here](https://github.com/jamesaoverton/cmi-pb-terminology/blob/87f9ec7fd1c5125c64469da3943178c3dbf02e9a/src/script/load.py#L510)). So we only stand to gain by implementing this.
