### ISSUE TITLE
Implement insert_row

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/cmi-pb-terminology#57]
I had kind of forgotten about this, but we need an `insert_row()` function (parallel to `update_row()`) that can be called from the frontend code.

**Comment by lmcmicu** [comment]
How is the new row number to be determined? For rows that are loaded from the .tsv files this corresponds to the actual position of the row in the file. For new rows should we simply increment the greatest row number by 1?

**Comment by jamesaoverton** [comment]
Yes, that sounds right to me.
