### ISSUE TITLE
Use more information from the terminology Google Sheet

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/cmi-pb-terminology#9]
This Google Sheet drives the CMI-PB terminology:

https://docs.google.com/spreadsheets/d/1xCrNM8Rv3v04ii1Fd8GMNTSwHzreo74t4DGsAeTsMbk/edit#gid=0

We're only using a few of the columns, but more of this information should appear in the OWL:

A. 'Column': it would be helpful to have this as some sort of annotation, with a custom CMI-PB predicate, but we probably don't want to show it in the terminology browser
B. 'Label': We need a new predicate for this like "CMI-PB alternative term", and we want to use it as the short_label for search tables
C. 'CURIE': Bjoern would just like this filled out.

I think we want a new CMI-PB prefix for this. I'm not sure what the base IRI should be, probably `http://cmi-pb.org/terminology/CMI-PB_`, but we might need to change that later.

**Comment by beckyjackson** [comment]
For "Column", what do we want to call the property? Maybe just `CMI-PB:column`, with the label "CMI-PB column"?

Currently, "Label" (B) is `CMI-PB:shortLabel` ("short label"). Do you want to change this to `CMI-PB:alternativeTerm`?

**Comment by jamesaoverton** [comment]
I'm fine with `CMI-PB:column`. I think Bjoern prefers "CMI-PB alternative term", so I guess the predicate is better as `CMI-PB:alternativeTerm`. Thanks!
